export type Treatment = {
  slug: string;
  title: string;
  image: string;
  description: string[];
  benefits: string[];
};

export const treatments: Treatment[] = [
  {
    slug: "steam-bath",
    title: "Steam Bath",
    image: "/treatments/steambath.png",
    description: [
      "Ayurvedic steam bath, known in classical texts as Swedana, is one of the foundational preparatory procedures in traditional Kerala medicine. The therapy involves exposing the entire body — or specific regions — to a continuous flow of warm, medicated herbal steam generated by boiling a carefully selected blend of therapeutic plants. The choice of herbs is tailored to the individual's body constitution (Prakriti) and the specific condition being treated.",
      "During the session, the patient sits comfortably inside a specially designed steam cabinet while the head remains outside, ensuring no overheating of the cranial region. The herbal steam penetrates the pores of the skin, softens the tissues, and begins dissolving the accumulated toxins (Ama) that are lodged in the deeper layers of the body. A typical session lasts between 15 and 30 minutes depending on the individual's tolerance and therapeutic need.",
      "Swedana is most commonly used as a preparatory step before deeper Ayurvedic treatments such as Pizhichil, Navarakizhi, or Abhyanga. By opening the channels of the body (Srotas) and loosening morbid matter, it dramatically enhances the effectiveness of subsequent therapies. It also serves as a standalone treatment for conditions like chronic stiffness, cold and congestion, and musculoskeletal pain.",
      "At MMGurukkals, we use traditional wood-fired steam chambers with fresh herbal decoctions prepared on-site daily. Our therapists monitor the entire session closely to ensure comfort and safety, adjusting the steam intensity based on your real-time feedback. Most patients feel immediate lightness, warmth, and relief after a single session.",
    ],
    benefits: [
      "Removes toxins and impurities through therapeutic perspiration",
      "Relieves muscle stiffness, joint pain, and chronic aches",
      "Improves blood circulation and skin tone",
      "Reduces stress, tension, and promotes deep relaxation",
      "Opens pores and prepares tissues for better absorption of medicated oils",
    ],
  },
  {
    slug: "pizhichil",
    title: "Pizhichil",
    image: "/premiumBlog.webp",
    description: [
      "Pizhichil, often referred to as the 'treatment of kings' or Rajachikitsa, is one of the most opulent and deeply therapeutic treatments in the Ayurvedic tradition. The name itself derives from the Malayalam word for 'squeezing' — a reference to the continuous squeezing of cloth soaked in warm medicated oil over the patient's body. This treatment combines two classical Ayurvedic therapies — Snehana (oleation) and Swedana (sudation) — into a single, powerful, synergistic session.",
      "The procedure involves two to four trained therapists working in perfect synchrony. Large quantities of specially prepared warm medicated oil — selected based on the patient's condition and constitution — are poured in a slow, continuous, rhythmic stream over the entire body from cloth bundles held above. Simultaneously, the therapists perform a coordinated full-body massage, ensuring the warm oil penetrates deeply into every layer of tissue. A typical Pizhichil session lasts 60 to 90 minutes.",
      "The sustained warmth of the oil combined with the rhythmic pressure of the massage creates a deeply penetrating therapeutic effect. It nourishes the nervous system, strengthens and tones the muscles, lubricates the joints, and promotes the elimination of deeply embedded toxins from the tissues. Pizhichil is particularly renowned as the definitive Ayurvedic treatment for conditions involving the nervous system, including hemiplegia, paraplegia, and various forms of muscular atrophy.",
      "At MMGurukkals, Pizhichil is performed in a purpose-built traditional wooden droni (treatment table) that allows the oil to pool and be recycled during the session. Our practitioners are trained in classical Ashtavaidya methods passed down through generations of Kerala's hereditary physicians. This is a deeply meditative experience that leaves most patients in a state of profound relaxation and physical renewal.",
    ],
    benefits: [
      "Deeply nourishes and rejuvenates the entire body",
      "Relieves pain and inflammation in joints and muscles",
      "Highly effective for arthritis, paralysis, and neuromuscular disorders",
      "Improves skin texture, complexion, and lustre",
      "Promotes deep mental calmness and reduces anxiety and stress",
    ],
  },
  {
    slug: "shirodhara",
    title: "Shirodhara",
    image: "/premium.webp",
    description: [
      "Shirodhara is one of the most iconic and profoundly calming treatments in the entire canon of Ayurvedic medicine. The word is a Sanskrit compound: 'Shiro' meaning head, and 'Dhara' meaning flow or stream. The treatment involves a continuous, gentle, unbroken stream of warm medicated liquid — traditionally sesame oil infused with herbs, though buttermilk, herbal decoctions, or milk may also be used depending on the condition — poured steadily onto the centre of the forehead, precisely at the point known as the 'Ajna' or third eye.",
      "The patient lies in a deeply comfortable position on the traditional wooden droni. The liquid is held in a suspended clay or copper pot with a small hole at the base, allowing it to flow in a thin, steady stream at the precise temperature and height required. The therapist gently swings the pot in a slow, pendulum-like rhythm so that the stream moves across the forehead in a soothing oscillating pattern. The session typically lasts 45 to 60 minutes.",
      "The physiological and neurological effects of Shirodhara are remarkable. The steady, rhythmic pressure of the warm liquid on the forehead activates the hypothalamic-pituitary axis, stimulates specific nerve endings, and induces a meditative state similar to deep sleep. It is considered among the most effective Ayurvedic treatments for regulating the autonomic nervous system, reducing cortisol levels, and restoring balance to the mind.",
      "Shirodhara is indicated for a wide range of conditions including chronic stress and anxiety, depression, insomnia, migraine, tinnitus, premature greying, hair loss, hypertension, and certain neurological conditions. At MMGurukkals, our Shirodhara oils are freshly prepared using traditional Kerala recipes, and the session is always preceded by a head and neck massage to prepare the tissues and deepen the therapeutic effect.",
    ],
    benefits: [
      "Calms and deeply rejuvenates the central nervous system",
      "Relieves chronic stress, anxiety, and mental fatigue",
      "Highly effective for insomnia and sleep disorders",
      "Reduces headaches, migraines, and tinnitus",
      "Improves memory, concentration, and cognitive clarity",
    ],
  },
  {
    slug: "navarakizhi",
    title: "Navarakizhi",
    image: "/treatments/navarakizhi.png",
    description: [
      "Navarakizhi — also known by its Sanskrit name Shashtika Shali Pinda Sweda — is one of the most prized and deeply nourishing treatments in Kerala Ayurveda. 'Navara' refers to a special variety of red rice unique to Kerala that is harvested within 60 days, revered for its exceptional medicinal qualities. 'Kizhi' means bolus or bundle. The treatment uses cloth boluses packed with Navara rice that has been cooked in a nutritive preparation of milk and a herbal decoction of Bala (Sida cordifolia) and other tonifying herbs.",
      "The procedure begins with a preparatory full-body oil massage using warm medicated oil. The therapists then take the warm, freshly prepared Navara boluses — at the correct temperature of approximately 45°C — and apply them in steady, rhythmic strokes across the entire body, periodically re-dipping them into the warm milk-herb preparation to maintain their temperature and nutritive potency. The massage movements follow the channels of the body and the direction of the muscles and tendons. Sessions typically last 60 to 90 minutes.",
      "At a tissue level, Navarakizhi works primarily on the Mamsa Dhatu (muscle tissue), Asthi Dhatu (bone tissue), and Majja Dhatu (nerve tissue). The unique combination of the Navara rice — rich in proteins and complex carbohydrates — with the milk medium and herbal decoction creates a deeply bio-available nutritive therapy that strengthens, builds, and repairs tissues from the outside in. The warmth and gentle pressure open the skin's pores, facilitating deep absorption of these nutrients.",
      "Navarakizhi is particularly indicated for conditions involving muscular weakness, wasting, and degeneration — including muscular dystrophy, hemiplegia, post-stroke rehabilitation, and neurological conditions. It is also highly effective as a rejuvenating (Rasayana) therapy for athletes, the elderly, and those recovering from illness. After a course of Navarakizhi, most patients experience significantly improved strength, skin quality, joint mobility, and overall vitality.",
    ],
    benefits: [
      "Strengthens muscles, ligaments, tendons, and joints",
      "Deeply nourishes and rebuilds body tissues (Dhatus)",
      "Highly effective for muscular dystrophy and neurological conditions",
      "Improves skin health, tone, and complexion",
      "Reduces chronic inflammation, stiffness, and deep-seated pain",
    ],
  },
  {
    slug: "podi-kizhi",
    title: "Podi Kizhi",
    image: "/treatments/podikizhi.png",
    description: [
      "Podi Kizhi, known in Sanskrit as Churna Pinda Sweda, is a dry heat fomentation therapy that uses cloth boluses filled with specially formulated herbal powders (Churna). The word 'Podi' means powder in Malayalam, and the composition of the herbal powder blend is carefully selected by the physician based on the patient's condition and constitution. Common herbs used include Kolakulathadi Churna, Rasnadi Churna, and other warming, pain-relieving, and anti-inflammatory formulations.",
      "The boluses are heated in a pan with small amounts of medicated oil until the powders are hot and aromatic. The therapists — typically two working simultaneously on either side of the body — apply the heated boluses with firm, rhythmic strokes and pressure across the affected areas or the entire body. The boluses are periodically reheated throughout the session to maintain the therapeutic temperature. A session lasts between 45 and 60 minutes.",
      "Unlike oil-based kizhi treatments, Podi Kizhi is a predominantly dry therapy. The heat and bioactive compounds from the herbal powders penetrate deeply into the skin and underlying tissues, reducing swelling, dissolving accumulated deposits around joints, and stimulating circulation and lymphatic drainage. This makes it particularly effective for conditions where increased Kapha dosha or excess fluid retention is involved — such as swollen joints, obesity-related joint problems, and certain types of arthritis.",
      "Podi Kizhi is indicated for conditions including rheumatoid arthritis, osteoarthritis, inflammatory joint conditions, cervical and lumbar spondylosis, sports injuries, and post-fracture rehabilitation. It works exceptionally well in combination with other Ayurvedic treatments such as Virechana (purgation therapy) or as part of a Panchakarma programme. At MMGurukkals, our herbal powder blends are freshly prepared and the formulation is reviewed by our physicians before each course of treatment.",
    ],
    benefits: [
      "Relieves pain and swelling in arthritic and inflamed joints",
      "Effective for cervical spondylosis, lumbar spondylosis, and sports injuries",
      "Reduces joint stiffness and improves range of motion",
      "Stimulates blood circulation and lymphatic drainage",
      "Promotes lightness in the body and reduces heaviness from Kapha excess",
    ],
  },
  {
    slug: "elakizhi",
    title: "Elakizhi",
    image: "/treatments/elakizhi.png",
    description: [
      "Elakizhi — known in Sanskrit as Patra Pinda Sweda — is a rejuvenating herbal bolus treatment that uses fresh medicinal leaves and plant materials as its primary therapeutic medium. 'Ela' means leaf in Malayalam, and the treatment harnesses the powerful bioactive compounds found in freshly harvested medicinal plants. The specific combination of leaves used varies by season, availability, and the patient's condition, but typically includes Eranda (castor), Arka (calotropis), Nirgundi (Vitex negundo), Drumstick leaves, Lemon, and other locally sourced therapeutic plants.",
      "The leaves are chopped and sautéed in a blend of medicated oil, grated coconut, lemon, and selected herbal powders until they become warm, fragrant, and slightly wilted. This aromatic mixture is then tightly packed into cloth boluses. The therapists dip the boluses in warm medicated oil and apply them in firm, rhythmic strokes across the body — typically working in pairs to ensure uniform coverage and consistent temperature. The boluses are periodically refreshed in warm oil throughout the session.",
      "The combination of localised heat, medicated oil, and the fresh bioactive compounds from the leaves creates a treatment of remarkable depth and effectiveness. The essential oils, alkaloids, and other phytochemicals present in the fresh leaves are released by heat and penetrate the skin to act directly on inflamed tissues, nerve endings, and joints. The therapy provides both anti-inflammatory and analgesic effects while simultaneously nourishing and detoxifying the tissues.",
      "Elakizhi is particularly effective for conditions involving chronic musculoskeletal pain, degenerative joint conditions, osteoarthritis, cervical and lumbar spondylosis, sciatica, frozen shoulder, and nerve-related pain conditions. It is also used in sports medicine for muscle recovery and in post-injury rehabilitation. At MMGurukkals, we source our medicinal leaves fresh each morning from our own herbal garden to ensure maximum potency.",
    ],
    benefits: [
      "Relieves chronic pain and inflammatory musculoskeletal conditions",
      "Highly effective for osteoarthritis, cervical spondylosis, and sciatica",
      "Improves blood circulation and peripheral nerve function",
      "Reduces muscle spasms, stiffness, and tension",
      "Nourishes, detoxifies, and rejuvenates body tissues",
    ],
  },
  {
    slug: "nasya",
    title: "Nasya",
    image: "/treatments/naysa.png",
    description: [
      "Nasya is one of the five classical Panchakarma therapies in Ayurveda, and it represents one of the most sophisticated and targeted treatment modalities for conditions affecting the head, neck, and upper respiratory system. The term refers to the administration of medicated substances — oils, herbal juices, powders, or medicated ghee — through the nasal passages. According to Ayurvedic anatomy, the nose is considered the 'doorway to the brain and consciousness' (Nasahi Shiraso Dwaram), making this pathway uniquely effective for reaching and treating the structures of the head.",
      "The treatment begins with a preparatory facial and neck massage using warm medicated oil, followed by gentle heat application (Swedan) to the face and neck to open the channels. The patient then lies with the head tilted slightly back, and the prescribed medicated oil or preparation is carefully instilled into each nostril in a measured dose. The patient breathes slowly and deeply as the medication is absorbed through the nasal mucosa and travels into the sinuses, cranial cavities, and deeper structures. The session concludes with gargling and gentle massage of the neck and shoulders.",
      "There are several types of Nasya classified in classical Ayurvedic texts based on the nature of the substance used and the therapeutic intent. Snehana Nasya uses medicated oils for nourishing and pacifying; Shodhana Nasya uses more intense preparations for purifying the channels; Pratimarsha Nasya is a daily prophylactic type using a drop of plain oil. The type prescribed depends on the patient's condition, dosha imbalance, and the season of treatment.",
      "Nasya is indicated for conditions including chronic sinusitis, nasal polyps, allergic rhinitis, migraine, cluster headaches, cervical spondylosis, facial paralysis, tinnitus (ringing in the ears), loss of smell or taste, vision problems, hair loss, and premature greying. It is also highly valued as a preventive and longevity (Rasayana) practice when done daily. At MMGurukkals, Nasya preparations are prescribed and supervised by our Ayurvedic physicians to ensure the correct formulation for each patient.",
    ],
    benefits: [
      "Clears sinuses, relieves nasal congestion, and treats chronic sinusitis",
      "Effective for migraines, cluster headaches, and chronic headaches",
      "Improves vision, hearing, voice quality, and sense of smell",
      "Enhances mental clarity, focus, and cognitive function",
      "Promotes healthy hair growth and prevents premature greying",
    ],
  },
  {
    slug: "janu-basti",
    title: "Janu Basti (For Knee Pain)",
    image: "/treatments/knee.png",
    description: [
      "Janu Basti is a highly specialised and targeted Ayurvedic treatment designed specifically to treat the knee joint — one of the most complex and commonly affected joints in the human body. 'Janu' means knee in Sanskrit, and 'Basti' refers to a retention or pool. The treatment involves building a small dam-like ring of black gram dough (urad dal) around the knee joint and filling it with warm medicated oil, which is retained for 30 to 45 minutes. The oil is periodically replaced as it cools to maintain the therapeutic temperature throughout the session.",
      "The choice of medicated oil is critical and is determined by the physician based on the specific condition of the knee. For degenerative conditions like osteoarthritis, deeply nourishing and lubricating oils such as Ksheerabala Thailam or Mahanarayan Thailam are typically used. For inflammatory conditions, oils with potent anti-inflammatory properties are preferred. The patient lies in a comfortable position with the knee relaxed, and the oil is maintained at a precise therapeutic temperature of approximately 40–45°C throughout the session.",
      "The sustained contact of warm medicated oil with the knee creates a series of therapeutic effects. The heat dilates the local blood vessels, dramatically improving circulation to the joint and surrounding tissues. The bioactive compounds in the medicated oil penetrate the skin and joint capsule, reaching the synovial membrane, cartilage, and ligaments. This results in improved lubrication of the joint, reduction in inflammation, nourishment of cartilage, and relaxation of the periarticular muscles and tendons.",
      "Janu Basti is indicated for osteoarthritis of the knee, rheumatoid arthritis affecting the knee, post-surgical knee rehabilitation, sports injuries including ligament and meniscus issues, and any condition causing chronic knee pain and stiffness. A course of 7 to 14 consecutive sessions is typically recommended for best results. At MMGurukkals, Janu Basti is often combined with Abhyanga (oil massage), Podi Kizhi, or other treatments as part of a comprehensive knee rehabilitation programme.",
    ],
    benefits: [
      "Relieves knee pain from arthritis, injuries, and degeneration",
      "Strengthens the muscles and ligaments supporting the knee joint",
      "Lubricates the knee joint, reducing stiffness and friction",
      "Improves range of motion and functional mobility of the knee",
      "Slows further degeneration of cartilage and joint structures",
    ],
  },
  {
    slug: "skin-hair-care",
    title: "Skin & Hair Care",
    image: "/treatments/hair.png",
    description: [
      "Ayurvedic Skin and Hair Care at MMGurukkals is a comprehensive, individualised approach to treating and maintaining the health of the skin and scalp using time-tested herbal formulations and therapeutic techniques. Unlike modern dermatological treatments that address only surface symptoms, the Ayurvedic approach identifies and treats the underlying doshic imbalances and internal factors — such as impaired digestion, accumulated toxins (Ama), and lifestyle factors — that manifest as external skin and hair conditions.",
      "Our skin treatments utilise a range of classical Ayurvedic modalities including Lepa (herbal paste applications), Udwarthana (herbal powder massage), Takra Dhara (medicated buttermilk therapy), and targeted internal detoxification therapies. Herbs such as neem, turmeric, manjistha, chandana (sandalwood), vetiver, and kumkumadi are selected and combined based on the individual's skin type, current condition, and dosha constitution. All preparations are made fresh using organic, locally sourced ingredients.",
      "For hair concerns, our treatments include Shiroabhyanga (therapeutic scalp massage with medicated oils), Shirolepa (herbal hair mask applications), Nasya (nasal oil therapy for deep scalp nourishment), and Shirodhara (medicated oil stream on the scalp). These therapies address the root causes of hair loss — including scalp circulation, follicle nutrition, stress-related hair fall, and hormonal imbalance — rather than merely treating the surface. Herbs like brahmi, bhringraj, amla, hibiscus, and sesame are core to our hair care formulations.",
      "Conditions commonly treated through our Skin & Hair Care programme include acne and acne scarring, eczema, psoriasis, dermatitis, hyperpigmentation, dry and dull skin, hair thinning and loss (Alopecia), dandruff, dry scalp, and premature greying. A full assessment and consultation with our Ayurvedic physician precedes all treatment programmes to ensure a fully personalised therapeutic approach.",
    ],
    benefits: [
      "Treats acne, eczema, psoriasis, and chronic skin conditions",
      "Promotes hair growth and significantly reduces hair fall",
      "Nourishes and deeply moisturises skin for a healthy, lasting glow",
      "Addresses dandruff, dry scalp, and premature greying",
      "Detoxifies the skin through targeted herbal therapies",
    ],
  },
  {
    slug: "ultrasound-therapy",
    title: "Ultrasound Therapy",
    image: "/treatments/ultrasound.png",
    description: [
      "Ultrasound therapy is a well-established physiotherapy modality that uses high-frequency sound waves — typically between 1 and 3 MHz — to deliver therapeutic energy deep into the body's soft tissues. The sound waves produce two distinct therapeutic effects: a thermal effect (deep heating of tissues) and a non-thermal or mechanical effect (micro-vibrations at the cellular level called cavitation and acoustic streaming). These effects together accelerate tissue healing, reduce inflammation, and relieve pain.",
      "During a session, the therapist applies a specialised conductive gel to the skin over the treatment area and then moves a smooth transducer head in slow, overlapping circles over the surface. The gel ensures efficient transmission of the sound waves into the tissues. The treatment is generally painless — most patients feel a mild, pleasant warmth in the treated area. Sessions last between 5 and 15 minutes depending on the area and condition, and a course of 6 to 12 sessions is typically recommended.",
      "At MMGurukkals, we integrate modern ultrasound therapy with Ayurvedic principles to create a holistic treatment protocol. We frequently combine ultrasound therapy with warm medicated oil application, marma point stimulation, and other Ayurvedic therapies to create synergistic effects that neither modality can achieve alone. The ultrasound enhances the penetration of topically applied medicated oils, making it a powerful bridge between traditional and modern healing approaches.",
      "Ultrasound therapy is indicated for a wide range of musculoskeletal conditions including tendinitis (shoulder, elbow, knee, ankle), bursitis, plantar fasciitis, carpal tunnel syndrome, frozen shoulder, muscle strains and tears, ligament sprains, post-surgical scar tissue, and chronic back pain. It is particularly effective for conditions involving scar tissue or calcification where deep tissue mobilisation is needed.",
    ],
    benefits: [
      "Reduces chronic pain and inflammation in muscles and tendons",
      "Accelerates healing of soft tissue injuries and strains",
      "Breaks down scar tissue, adhesions, and calcifications",
      "Improves local circulation and tissue metabolism",
      "Effective for tendinitis, bursitis, frozen shoulder, and plantar fasciitis",
    ],
  },
  {
    slug: "tens-therapy",
    title: "TENS Therapy",
    image: "/treatments/tans.png",
    description: [
      "TENS — Transcutaneous Electrical Nerve Stimulation — is a non-invasive, drug-free pain management therapy that uses controlled low-voltage electrical impulses delivered through electrode pads placed on the skin to modulate pain signals and stimulate the body's natural pain-relief mechanisms. The therapy is based on the Gate Control Theory of pain, which proposes that the electrical stimulation of sensory nerves effectively 'closes the gate' on pain signals travelling to the brain, providing immediate and significant relief.",
      "The TENS unit is a compact electronic device connected to self-adhesive electrode pads. The therapist places these pads around or over the painful area and adjusts the frequency, intensity, and pulse width of the electrical current to match the patient's condition and tolerance. Two main modes are used: high-frequency TENS (conventional TENS) produces immediate pain relief by blocking nerve signals, while low-frequency TENS (acupuncture-like TENS) stimulates the production of endorphins — the body's natural pain-killing chemicals — for longer-lasting relief.",
      "At MMGurukkals, TENS therapy is delivered by trained physiotherapists and is frequently combined with Ayurvedic treatments to maximise effectiveness. For example, TENS applied over Marma points can enhance the effects of Marma therapy; when used in conjunction with warm medicated oil application, it significantly deepens tissue penetration and pain relief. This integrative approach is one of the distinctive features of the MMGurukkals treatment philosophy.",
      "TENS therapy is suitable for a broad range of acute and chronic pain conditions including lower back pain, cervical and lumbar spondylosis, arthritis, fibromyalgia, nerve pain (neuropathy), post-surgical pain, menstrual pain, sports injuries, and chronic regional pain syndrome. It is safe for long-term use and can be combined with virtually any other treatment modality without adverse interactions.",
    ],
    benefits: [
      "Provides immediate, drug-free relief from acute and chronic pain",
      "Reduces pain from arthritis, back pain, and nerve conditions",
      "Stimulates endorphin release for long-lasting natural pain relief",
      "Safe, non-invasive, and suitable for long-term pain management",
      "Effectively combined with Ayurvedic therapies for enhanced results",
    ],
  },
  {
    slug: "bone-setting",
    title: "Bone Setting",
    image: "/treatments/bone.png",
    description: [
      "Bone Setting (Asthi Sandhi Chikitsa) is a highly specialised traditional healing practice with roots in Kerala's ancient medical traditions, including Ayurveda and the warrior healing arts of Kalaripayattu. Our bone setters have inherited this rare knowledge through an unbroken lineage of family transmission spanning many generations. The practice involves the assessment, manual reduction, and stabilisation of fractures, dislocations, and complex joint injuries using entirely natural means.",
      "The treatment begins with a careful physical assessment of the injury — including assessment of the fracture type, displacement, soft tissue involvement, and the patient's overall health. Unlike conventional orthopaedics, the traditional bone setter relies entirely on the sense of touch, accumulated clinical experience, and an intimate understanding of anatomy developed through years of training. The setting procedure involves skilled manual manipulation to guide bones back to their correct anatomical position, followed by immobilisation using herbal poultices and traditional splints made from bamboo or other natural materials.",
      "After the bone is set, the injured area is treated with a series of specialised herbal applications — including freshly prepared poultices made from anti-inflammatory plants such as turmeric, castor root, and Cissus quadrangularis (bone-healing herb known as Hadjod) — which are changed daily. Warm medicated oil massages are also applied to the surrounding tissues to prevent atrophy, maintain circulation, and reduce secondary pain. The patient receives detailed guidance on diet, rest, and activity restrictions to support optimal healing.",
      "Traditional bone setting is particularly valued for cases where surgery is not desired or not accessible, for injuries in children, and for complex soft tissue injuries around joints where conventional medicine offers limited conservative options. Our practitioners have successfully treated fractures, dislocations, ligament injuries, and joint instabilities that were previously considered surgical candidates. A full consultation and assessment is conducted before every treatment.",
    ],
    benefits: [
      "Reduces dislocated joints and treats fractures without surgery",
      "Uses herbal applications to promote faster, stronger bone healing",
      "Reduces recovery time compared to conventional immobilisation methods",
      "Restores full joint mobility and function post-injury",
      "Minimises long-term risk of joint stiffness and disability",
    ],
  },
  {
    slug: "traditional-bone-setting",
    title: "Traditional Bone Setting",
    image: "/treatments/tbone.png",
    description: [
      "Traditional Bone Setting at MMGurukkals represents the most advanced and comprehensive expression of Kerala's ancient orthopaedic healing tradition. Drawing from both the Ayurvedic system of Asthi Chikitsa and the battle-tested healing methods of Kalaripayattu martial arts, our senior practitioners apply techniques that have been refined over centuries of treating complex combat and training injuries. This form of bone setting goes beyond fractures and dislocations to address deep structural imbalances in the musculoskeletal system.",
      "The assessment process is uniquely thorough — our practitioners examine not only the site of injury but the entire kinetic chain, identifying compensatory patterns, subtle joint misalignments, and the impact of the injury on the flow of Prana (vital energy) through the Marma points. This holistic evaluation guides a treatment plan that addresses both the immediate injury and its underlying structural context. Treatment sessions involve a combination of skilled manual manipulation, deep tissue herbal oil massage, and precisely targeted Marma point therapy.",
      "A hallmark of Traditional Bone Setting at MMGurukkals is the use of freshly prepared herbal bandages and poultices that are applied directly to the injured site. These formulations — developed and refined by our lineage — typically include combinations of Laksha (lac), Guggulu resin, Shilajatu (mineral pitch), Hadjod (Cissus quadrangularis), Ashwagandha, and other osteogenic (bone-building) herbs. These preparations are believed to significantly accelerate mineralisation and the laying down of new bone matrix.",
      "Traditional Bone Setting is appropriate for complex fractures, multiple fractures, old or improperly healed injuries, severe joint dislocations, sports injuries involving ligament and tendon damage, and conditions such as chronic joint instability. It is also used as a comprehensive rehabilitation programme following conventional orthopaedic surgery to restore strength, flexibility, and functional movement. At MMGurukkals, a minimum 3-day assessment period is recommended before the initiation of a full treatment programme.",
    ],
    benefits: [
      "Treats complex fractures, dislocations, and structural joint disorders",
      "Applies osteogenic herbal formulations to accelerate bone regeneration",
      "Promotes faster and stronger structural recovery",
      "Relieves associated muscle tension, nerve compression, and referred pain",
      "Suitable for sports injuries, work injuries, and age-related bone conditions",
    ],
  },
  {
    slug: "marma-kizhi",
    title: "Marma Kizhi",
    image: "/treatments/marmakizhi.png",
    description: [
      "Marma Kizhi is a uniquely powerful treatment that unites two of the most sophisticated therapeutic systems in Kerala's healing tradition: the ancient science of Marma therapy — the stimulation of vital energy junctions in the body — with the heating and medicinal benefits of herbal bolus (kizhi) therapy. 'Marma' refers to the 107 vital points identified in classical Ayurvedic and Kalaripayattu texts where muscles, veins, tendons, bones, and joints meet — points that are considered gateways for the flow of Prana (life force) through the body.",
      "The session begins with the therapist carefully mapping the relevant Marma points based on the patient's condition and therapeutic goals. Warm herbal boluses — filled with a specialised blend of herbs selected for their Marma-activating properties, including Bala, Ashwagandha, Shatavari, and warming spices — are then applied with precise, deliberate pressure directly onto these vital points. The combination of heat, herbal compounds, and targeted pressure creates a treatment that simultaneously works on the physical tissues and the subtle energy channels (Nadis) of the body.",
      "The effects of Marma Kizhi are felt both locally and systemically. Locally, the treatment relieves deep-seated pain, reduces inflammation, and relaxes contracted muscles around the Marma sites. Systemically, the activation of key Marma points is understood in Ayurveda to regulate the flow of Prana throughout the body, restore hormonal balance, improve the function of associated organs, and promote the natural intelligence of the body's self-healing mechanisms.",
      "Marma Kizhi is indicated for conditions including chronic musculoskeletal pain, fibromyalgia, post-stroke rehabilitation, neurological disorders, fatigue syndromes, traumatic injuries, and conditions where conventional treatments have provided limited relief. It is also used as a preventive and rejuvenating therapy for those seeking to optimise vitality and resilience. At MMGurukkals, Marma Kizhi is administered only by therapists who have received specific training in Marma Vidya.",
    ],
    benefits: [
      "Activates vital Marma points to restore the flow of Prana",
      "Relieves deep-seated musculoskeletal and chronic pain",
      "Improves nerve function, coordination, and motor recovery",
      "Balances the body's vital energy and supports organ health",
      "Promotes deep physical and mental well-being",
    ],
  },
  {
    slug: "kalari-uzhichil",
    title: "Kalari Uzhichil",
    image: "/treatments/uzhichil.png",
    description: [
      "Kalari Uzhichil is a traditional therapeutic massage system that emerged directly from the training and healing practices of Kalaripayattu — the ancient Kerala martial art considered the mother of all Asian martial arts. For thousands of years, Kalaripayattu masters (Gurukkal) developed precise massage techniques to prepare warriors' bodies for combat, treat battle injuries, and restore physical and mental peak performance. Over centuries, these techniques evolved into a comprehensive therapeutic massage system rooted equally in Ayurvedic principles and the biomechanical insights of the Kalari tradition.",
      "The treatment uses warm medicated oils (Thailam) specially prepared according to classical Kerala Ayurvedic recipes — the specific oil chosen based on the patient's condition, constitution, and the season. The therapist applies the oil with deep, rhythmic strokes along the channels of the body, working systematically from the feet upwards. Unlike conventional massage, Kalari Uzhichil applies highly specific pressure at Marma points and along the tendinomuscular channels (Siras and Snayu) identified in Kalaripayattu anatomy, creating effects that extend far beyond simple muscle relaxation.",
      "One of the distinctive features of Kalari Uzhichil is its effect on the body's fascia — the connective tissue matrix that permeates every structure of the body. The deep, directional strokes of the Kalari massage system release fascial restrictions, improve joint mobility, and restore the natural tensegrity of the musculoskeletal system. This is why athletes, martial artists, and those recovering from structural injuries find particular benefit in this treatment.",
      "Kalari Uzhichil is indicated for musculoskeletal pain, sports injuries, joint stiffness, spondylosis, paralysis, neurological conditions, and as a general rejuvenation and fitness therapy. A full course consists of 7 to 21 consecutive daily sessions for therapeutic purposes. At MMGurukkals, our Kalari Uzhichil practitioners are trained directly in the living Kalaripayattu lineage, ensuring complete authenticity of technique and intention.",
    ],
    benefits: [
      "Relieves deep muscle tension, joint stiffness, and chronic pain",
      "Stimulates Marma points to restore the flow of vital energy",
      "Enhances flexibility, functional strength, and body coordination",
      "Improves circulation, detoxifies tissues, and accelerates recovery",
      "Promotes deep relaxation, mental clarity, and stress resilience",
    ],
  },
  {
    slug: "kalari-marma-herbal-bandage",
    title: "Kalari Marma Herbal Bandage",
    image: "/treatments/marmaherbal.png",
    description: [
      "The Kalari Marma Herbal Bandage is a remarkable specialised treatment drawn directly from the battlefield medicine of Kalaripayattu. Historically, when warriors sustained severe injuries during training or combat, the Gurukkal (master) would apply precisely prepared herbal preparations directly to the wound or injury site and secure them with traditional bandages made from natural fibres. This technique — refined over millennia of treating acute and traumatic injuries — represents one of the most concentrated and effective forms of topical herbal therapy available in traditional medicine.",
      "The herbal preparation used in the bandage is freshly made for each patient and customised to the nature and stage of the injury. It typically consists of a combination of anti-inflammatory herbs (such as turmeric, castor root, and Nirgundi), wound-healing and tissue-regenerating plants (such as Manjistha, Hadjod, and Kumari/Aloe), and tonifying herbs that build strength in the healing tissues. These are ground into a paste with an appropriate medium — sesame oil, castor oil, or herbal decoction — and applied warm directly to the skin over the injury site.",
      "The application technique itself carries therapeutic significance. The paste is applied with targeted pressure at specific Marma points around the injury site, and the bandaging technique is drawn from the classical Kalaripayattu method — applying controlled, graduated compression that supports the healing tissues without impeding circulation. The bandage is typically changed every 24 hours, and each change is accompanied by a brief assessment of healing progress and an oil massage to prevent stiffness.",
      "The Kalari Marma Herbal Bandage is particularly indicated for acute sprains and ligament injuries, fractures and post-reduction support, deep muscle tears, joint dislocations post-reduction, and post-surgical wound healing. It is also used for chronic conditions such as non-healing wounds, old injuries with persistent pain, and post-fracture complications. At MMGurukkals, this treatment is available as a standalone therapy or as part of our comprehensive injury rehabilitation programmes.",
    ],
    benefits: [
      "Dramatically accelerates healing of sprains, strains, and fractures",
      "Reduces inflammation and swelling rapidly",
      "Provides anti-bacterial and anti-inflammatory herbal protection",
      "Promotes tissue regeneration and wound healing at the injury site",
      "Effective for sports injuries, work-related injuries, and post-surgical recovery",
    ],
  },
  {
    slug: "chavitti-uzhichil",
    title: "Chavitti Uzhichil",
    image: "/treatments/chavitti.png",
    description: [
      "Chavitti Uzhichil is among the most visually striking and therapeutically powerful treatments in the Kalaripayattu healing tradition. The name translates literally as 'foot massage' — 'Chavitti' meaning foot pressure in Malayalam — but this description barely captures the sophistication of this ancient art. The therapist performs the entire treatment using their feet, holding overhead ropes for balance and leverage, applying controlled weight and directional pressure across the patient's body in a choreographed sequence that requires years of dedicated training to master.",
      "Before the session begins, the patient receives a generous application of warm medicated oil over the entire body. The therapist then mounts the treatment platform, takes hold of the ropes above, and begins applying the soles and heels of their feet to the patient's body in long, fluid strokes. The foot applies significantly more pressure than the hand can generate, making this treatment uniquely effective for working on deeply embedded muscular tension, thick fascial bands, and highly developed musculature. The therapist controls the pressure exquisitely through their grip on the ropes and body positioning.",
      "The therapeutic rationale of Chavitti Uzhichil is grounded in both Ayurvedic principles and the biomechanical insights of Kalaripayattu. The broad, warm surface of the foot can work over large muscle groups simultaneously, creating profound releases in the thoracolumbar fascia, iliotibial band, hamstrings, and the deep paraspinal muscles. The treatment follows specific sequences along the tendinomuscular channels (Siras) of the body, systematically opening each region and restoring optimal tension, mobility, and balance.",
      "Chavitti Uzhichil was historically used to condition the bodies of Kalaripayattu students before rigorous training, to rehabilitate injured fighters, and to maintain peak physical condition. Today, it remains particularly valued for athletes, dancers, and individuals with highly toned or overdeveloped musculature. It is also highly effective for chronic back pain, disc problems, deep hip and piriformis issues, and conditions where superficial massage has been unable to reach the source of pain.",
    ],
    benefits: [
      "Provides unparalleled deep tissue massage using controlled foot pressure",
      "Ideal for athletes, dancers, and those requiring intense deep tissue work",
      "Relieves chronic back pain, hip tension, and deep musculoskeletal issues",
      "Significantly improves flexibility and range of motion in all joints",
      "Stimulates Marma points and restores the flow of vital energy (Prana)",
    ],
  },
  {
    slug: "kalaripayattu",
    title: "Kalaripayattu",
    image: "/treatments/kalaripayattu.png",
    description: [
      "Kalaripayattu is one of the world's oldest surviving martial arts, with roots in Kerala that extend back more than 3,000 years. The name derives from 'Kalari' — the traditional training arena — and 'Payattu' — practice or exercise. Far more than a fighting system, Kalaripayattu is a complete system of physical, mental, and spiritual development that integrates martial combat forms, therapeutic healing practices, yogic disciplines, and philosophical wisdom into an inseparable whole. It is widely acknowledged as the ancestor of many Southeast and East Asian martial arts traditions.",
      "Training at MMGurukkals follows the classical curriculum of the Northern Kerala (Vadakkan) style, which emphasises flowing, full-body movements, high kicks, acrobatic sequences, and the use of traditional weapons including the long bamboo stick (Kettukari), short stick (Muchan), sword (Val), and flexible sword (Urumi). Training progresses systematically from foundational body conditioning exercises (Meippayattu), through combat sequences (Adavan), to weapons training and finally to the advanced healing arts of Marma therapy.",
      "As a therapeutic practice, Kalaripayattu training has profound effects on the body and mind. The dynamic, full-range movements develop extraordinary flexibility, joint health, and neuromuscular coordination. The conditioning exercises strengthen not just the superficial muscles but the deep stabilising muscles of the spine, pelvis, and shoulder girdle. The meditative focus required during practice — particularly during weapons training — cultivates a calm, alert, and resilient mind. Many practitioners report transformative improvements in posture, balance, body awareness, and stress management.",
      "At MMGurukkals, Kalaripayattu is offered both as a structured training discipline and as a therapeutic rehabilitation modality for conditions including musculoskeletal disorders, neurological rehabilitation, stress-related conditions, childhood development issues, and post-surgical recovery. Our Gurukkal (master) has decades of experience teaching students of all ages, abilities, and backgrounds. Sessions are available for individuals, small groups, and as residential immersion programmes.",
    ],
    benefits: [
      "Builds extraordinary strength, flexibility, and whole-body coordination",
      "Develops mental focus, emotional resilience, and stress management capacity",
      "Improves joint health, posture, balance, and body awareness",
      "Therapeutic for musculoskeletal conditions and neurological rehabilitation",
      "Connects practitioners deeply to Kerala's living cultural and martial heritage",
    ],
  },
];

export function getTreatmentBySlug(slug: string): Treatment | undefined {
  return treatments.find((t) => t.slug === slug);
}
